/**
 * @file Automatically generated by @tsed/barrels.
 */
export * from "./GooglePlacesController.js";
export * from "./HelloWorldController.js";
export * from "./LocationController.js";
export * from "./QuestController.js";
